# Generated by Django 4.1.5 on 2023-01-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_data', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ECDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensed_panel_rating', models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('400', '400')], default='50', max_length=30)),
                ('sensor_ct_rating', models.CharField(max_length=30)),
                ('circuit_breaker_a', models.CharField(max_length=30)),
                ('circuit_breaker_b', models.CharField(max_length=30)),
                ('c1', models.CharField(max_length=30, null=True)),
                ('c1ab', models.CharField(max_length=30, null=True)),
                ('c2', models.CharField(max_length=30, null=True)),
                ('c2ab', models.CharField(max_length=30, null=True)),
                ('c3', models.CharField(max_length=30, null=True)),
                ('c3ab', models.CharField(max_length=30, null=True)),
                ('c4', models.CharField(max_length=30, null=True)),
                ('c4ab', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lockoutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday1', models.CharField(max_length=30)),
                ('weekday2', models.CharField(max_length=30)),
                ('weekend1', models.CharField(max_length=30)),
                ('weekend2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WifiDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.alldetail')),
            ],
        ),
        migrations.CreateModel(
            name='DateTimeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_date', models.DateField(null=True)),
                ('_time', models.TimeField(null=True)),
                ('am_pm', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=30)),
                ('timezone', models.CharField(max_length=30)),
                ('reporter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.alldetail')),
            ],
        ),
    ]
