# Generated by Django 4.1.5 on 2023-02-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('local_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(choices=[('1234', '-------------Select Time Zone----------------'), ('-12.0', '(UTC -12:00) Eniwetok, Kwajalein'), ('-11.0', '(UTC -11:00) Midway Island, Samoa'), ('-10.0', '(UTC -10:00) Hawaii'), ('-9.0', '(UTC -09:00) Alaska'), ('-8.0', '(UTC -08:00) Pacific Time (US, Canada)'), ('-7.0', '(UTC -07:00) Mountain Time (US, Canada)'), ('-6.0', '(UTC -06:00) Central Time (US, Canada), Mexico City'), ('-5.0', '(UTC -05:00) Eastern Time (US, Canada), Bogota, Lima'), ('-4.0', '(UTC -04:00) Atlantic Time (Canada), Caracas, La Paz'), ('-3.5', '(UTC -03:30) Newfoundland'), ('-3.0', '(UTC -03:00) Brazil, Buenos Aires, Georgetown'), ('-2.0', '(UTC -02:00) Mid-Atlantic'), ('-1.0', '(UTC -01:00 hour) Azores, Cape Verde Islands'), ('0.0', '(UTC) London, Lisbon, Casablanca'), ('1.0', '(UTC +01:00 hour) Brussels, Copenhagen, Madrid, Paris'), ('2.0', '(UTC +02:00) Kaliningrad, South Africa'), ('3.0', '(UTC +03:00) Baghdad, Riyadh, Moscow, St. Petersburg'), ('3.5', '(UTC +03:30) Tehran'), ('4.0', '(UTC +04:00) Abu Dhabi, Muscat, Baku, Tbilisi'), ('4.5', '(UTC +04:30) Kabul'), ('5.0', '(UTC +05:00) Ekaterinburg, Islamabad, Karachi, Tashkent'), ('5.5', '(UTC +05:30) Bombay, Calcutta, Madras, New Delhi'), ('5.75', '(UTC +05:45) Kathmandu'), ('6.0', '(UTC +06:00) Almaty, Dhaka, Colombo'), ('7.0', '(UTC +07:00) Bangkok, Hanoi, Jakarta'), ('8.0', '(UTC +08:00) Beijing, Perth, Singapore, Hong Kong'), ('9.0', '(UTC +09:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk'), ('9.5', '(UTC +09:30) Adelaide, Darwin'), ('10.0', '(UTC +10:00) Eastern Australia, Guam, Vladivostok'), ('11.0', '(UTC +11:00) Magadan, Solomon Islands, New Caledonia'), ('12.0', '(UTC +12:00) Auckland, Wellington, Fiji, Kamchatka')], default='1234', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ECDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sensed_panel_rating', models.IntegerField(blank=True, default='100', null=True)),
                ('sensor_ct_rating', models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('400', '400')], default='200', max_length=30)),
                ('circuit_breaker_a', models.CharField(choices=[('15', '15'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], default='40', max_length=30)),
                ('circuit_breaker_b', models.CharField(choices=[('0', '0'), ('15', '15'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], default='0', max_length=30)),
                ('c1', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('max_amp1', models.IntegerField(default=0, null=True)),
                ('c1_circuit', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=30)),
                ('c2', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('max_amp2', models.IntegerField(default=0, null=True)),
                ('c2_circuit', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=30, null=True)),
                ('c3', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('max_amp3', models.IntegerField(default=0, null=True)),
                ('c3_circuit', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=30, null=True)),
                ('c4', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('max_amp4', models.IntegerField(default=0, null=True)),
                ('c4_circuit', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tou_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_from_1', models.CharField(blank=True, default=0, max_length=30, null=True)),
                ('weekday_to_1', models.CharField(blank=True, default=0, max_length=30, null=True)),
                ('weekday_from_2', models.CharField(blank=True, default=0, max_length=30, null=True)),
                ('weekday_to_2', models.CharField(blank=True, default=0, max_length=30, null=True)),
                ('weekend_from_1', models.CharField(blank=True, default=0, max_length=30, null=True)),
                ('weekend_to_1', models.CharField(blank=True, default=0, max_length=30, null=True)),
                ('weekend_from_2', models.CharField(blank=True, default=0, max_length=30, null=True)),
                ('weekend_to_2', models.CharField(blank=True, default=0, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WifiDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
    ]
