# Generated by Django 4.1.5 on 2023-01-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ecdetails_reporter_lockoutdetails_reporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datetimedetails',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='lockoutdetails',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='wifidetails',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='AllDetail',
        ),
    ]
