# Generated by Django 4.1.5 on 2023-01-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_datetimedetails_reporter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecdetails',
            name='c1',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='c1ab',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='c2',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='c2ab',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='c3',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='c3ab',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='c4',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='c4ab',
        ),
    ]
