# Generated by Django 4.1.5 on 2023-01-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_ecdetails_c1_remove_ecdetails_c1ab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecdetails',
            name='c1',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
