# Generated by Django 4.1.5 on 2023-01-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ecdetails_c1ab_ecdetails_c2_ecdetails_c2ab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecdetails',
            name='c1',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='c1ab',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='c2',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='c2ab',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='c3',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='c3ab',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='c4',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='c4ab',
        ),
        migrations.AlterField(
            model_name='ecdetails',
            name='circuit_breaker_a',
            field=models.CharField(choices=[('0', '0'), ('15', '15'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('100', '100')], default='15', max_length=30),
        ),
        migrations.AlterField(
            model_name='ecdetails',
            name='circuit_breaker_b',
            field=models.CharField(choices=[('0', '0'), ('15', '15'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('100', '100')], default='15', max_length=30),
        ),
        migrations.AlterField(
            model_name='ecdetails',
            name='sensor_ct_rating',
            field=models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('400', '400')], default='200', max_length=30),
        ),
    ]
