# Generated by Django 4.1.5 on 2023-01-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_ecdetails_c1_remove_ecdetails_c1ab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecdetails',
            name='circuit_breaker_a',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='circuit_breaker_b',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='sensor_ct_rating',
        ),
    ]
