# Generated by Django 4.1.5 on 2023-01-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_ecdetails_circuit_breaker_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecdetails',
            name='sensor_ct_rating',
            field=models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('400', '400')], default='200', max_length=30),
        ),
    ]
