# Generated by Django 4.1.5 on 2023-01-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_ecdetails_sensor_ct_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
