# Generated by Django 4.1.5 on 2023-01-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_ecdetails_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecdetails',
            name='circuit_breaker_a',
            field=models.CharField(choices=[('0', '0'), ('15', '15'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('100', '100')], default='15', max_length=30),
        ),
        migrations.AddField(
            model_name='ecdetails',
            name='circuit_breaker_b',
            field=models.CharField(choices=[('0', '0'), ('15', '15'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('100', '100')], default='15', max_length=30),
        ),
    ]
