# Generated by Django 4.1.5 on 2023-01-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_ecdetails_circuit_breaker_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecdetails',
            name='c1',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
