# Generated by Django 4.1.5 on 2023-01-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_ecdetails_c1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecdetails',
            name='c1ab',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
