# Generated by Django 4.1.5 on 2023-01-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_ecdetails_c1ab'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecdetails',
            name='max_amp1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ecdetails',
            name='c1ab',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=30),
        ),
    ]
