# Generated by Django 4.1.5 on 2023-01-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_ecdetails_max_amp1_alter_ecdetails_c1ab'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecdetails',
            name='c2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ecdetails',
            name='c2ab',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ecdetails',
            name='c3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ecdetails',
            name='c3ab',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ecdetails',
            name='c4',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ecdetails',
            name='c4ab',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ecdetails',
            name='max_amp2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ecdetails',
            name='max_amp3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ecdetails',
            name='max_amp4',
            field=models.IntegerField(null=True),
        ),
    ]
