# Generated by Django 4.1.5 on 2023-01-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_ecdetails_c2_ecdetails_c2ab_ecdetails_c3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datetimedetails',
            name='am_pm',
        ),
    ]
