# Generated by Django 4.1.5 on 2023-01-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_datetimedetails_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecdetails',
            name='circuit_breaker_a',
            field=models.CharField(choices=[('0', '0'), ('15', '15'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], default='15', max_length=30),
        ),
        migrations.AlterField(
            model_name='ecdetails',
            name='circuit_breaker_b',
            field=models.CharField(choices=[('0', '0'), ('15', '15'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], default='15', max_length=30),
        ),
        migrations.AlterField(
            model_name='lockoutdetails',
            name='weekday1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lockoutdetails',
            name='weekday2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lockoutdetails',
            name='weekend1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lockoutdetails',
            name='weekend2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
