# Generated by Django 4.1.5 on 2023-01-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_ecdetails_circuit_breaker_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockoutdetails',
            name='weekday2',
            field=models.CharField(default='12', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lockoutdetails',
            name='weekend2',
            field=models.CharField(default='12', max_length=30, null=True),
        ),
    ]
