# Generated by Django 4.1.5 on 2023-01-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_lockoutdetails_weekday2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockoutdetails',
            name='weekday1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lockoutdetails',
            name='weekday2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lockoutdetails',
            name='weekend1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lockoutdetails',
            name='weekend2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wifidetails',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wifidetails',
            name='ssid',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
