# Generated by Django 4.1.5 on 2023-01-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_lockoutdetails_weekday1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockoutdetails',
            name='weekday3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lockoutdetails',
            name='weekday4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lockoutdetails',
            name='weekend3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lockoutdetails',
            name='weekend4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
