# Generated by Django 4.1.5 on 2023-01-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_lockoutdetails_weekday3_lockoutdetails_weekday4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lockoutdetails',
            old_name='weekday1',
            new_name='weekday_from_1',
        ),
        migrations.RenameField(
            model_name='lockoutdetails',
            old_name='weekday2',
            new_name='weekday_from_2',
        ),
        migrations.RenameField(
            model_name='lockoutdetails',
            old_name='weekday3',
            new_name='weekday_to_1',
        ),
        migrations.RenameField(
            model_name='lockoutdetails',
            old_name='weekday4',
            new_name='weekday_to_2',
        ),
        migrations.RenameField(
            model_name='lockoutdetails',
            old_name='weekend1',
            new_name='weekend_from_1',
        ),
        migrations.RenameField(
            model_name='lockoutdetails',
            old_name='weekend2',
            new_name='weekend_from_2',
        ),
        migrations.RenameField(
            model_name='lockoutdetails',
            old_name='weekend3',
            new_name='weekend_to_1',
        ),
        migrations.RenameField(
            model_name='lockoutdetails',
            old_name='weekend4',
            new_name='weekend_to_2',
        ),
    ]
