# Generated by Django 4.1.5 on 2023-01-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_weekday1_lockoutdetails_weekday_from_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecdetails',
            name='circuit_breaker_a',
            field=models.CharField(choices=[('15', '15'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], default='40', max_length=30),
        ),
        migrations.AlterField(
            model_name='ecdetails',
            name='circuit_breaker_b',
            field=models.CharField(choices=[('15', '15'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], default='15', max_length=30),
        ),
        migrations.AlterField(
            model_name='ecdetails',
            name='sensed_panel_rating',
            field=models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('400', '400')], default='100', max_length=30),
        ),
    ]
