# Generated by Django 4.1.5 on 2023-01-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_ecdetails_circuit_breaker_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datetimedetails',
            old_name='_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='datetimedetails',
            old_name='_time',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='ecdetails',
            name='c1',
            field=models.CharField(default='A', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ecdetails',
            name='max_amp1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ecdetails',
            name='max_amp2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ecdetails',
            name='max_amp3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ecdetails',
            name='max_amp4',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
