# Generated by Django 4.1.5 on 2023-01-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename__date_datetimedetails_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datetimedetails',
            old_name='time',
            new_name='local_time',
        ),
    ]
