# Generated by Django 4.1.5 on 2023-01-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_time_datetimedetails_local_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecdetails',
            old_name='c2ab',
            new_name='c1_circuit',
        ),
        migrations.RenameField(
            model_name='ecdetails',
            old_name='c3ab',
            new_name='c2_circuit',
        ),
        migrations.RenameField(
            model_name='ecdetails',
            old_name='c4ab',
            new_name='c4_circuit',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='c1ab',
        ),
        migrations.RemoveField(
            model_name='ecdetails',
            name='c4',
        ),
    ]
