# Generated by Django 4.1.5 on 2023-01-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_rename_lockoutdetails_tou_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecdetails',
            name='c4',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
