# Generated by Django 4.1.5 on 2023-01-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_ecdetails_c4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimedetails',
            name='timezone',
            field=models.CharField(choices=[('none', '-------------Select Time Zone----------------'), ('-12.0', '(UTC -12:00) Eniwetok, Kwajalein'), ('-11.0', '(UTC -11:00) Midway Island, Samoa'), ('-10.0', '(UTC -10:00) Hawaii'), ('-9.0', '(UTC -09:00) Alaska'), ('-8.0', '(UTC -08:00) Pacific Time (US &amp; Canada)'), ('-7.0', '(UTC -07:00) Mountain Time (US &amp; Canada)'), ('-6.0', '(UTC -06:00) Central Time (US &amp; Canada), Mexico City'), ('-5.0', '(UTC -05:00) Eastern Time (US &amp; Canada), Bogota, Lima'), ('-4.0', '(UTC -04:00) Atlantic Time (Canada), Caracas, La Paz'), ('-3.5', '(UTC -03:30) Newfoundland'), ('-3.0', '(UTC -03:00) Brazil, Buenos Aires, Georgetown'), ('-2.0', '(UTC -02:00) Mid-Atlantic'), ('-1.0', '(UTC -01:00 hour) Azores, Cape Verde Islands'), ('1.0', '(UTC +01:00 hour) Brussels, Copenhagen, Madrid, Paris'), ('2.0', '(UTC +02:00) Kaliningrad, South Africa'), ('3.0', '(UTC +03:00) Baghdad, Riyadh, Moscow, St. Petersburg'), ('3.5', '(UTC +03:30) Tehran'), ('4.0', '(UTC +04:00) Abu Dhabi, Muscat, Baku, Tbilisi'), ('4.5', '(UTC +04:30) Kabul'), ('5.0', '(UTC +05:00) Ekaterinburg, Islamabad, Karachi, Tashkent'), ('5.5', '(UTC +05:30) Bombay, Calcutta, Madras, New Delhi'), ('5.75', '(UTC +05:45) Kathmandu'), ('6.0', '(UTC +06:00) Almaty, Dhaka, Colombo'), ('7.0', '(UTC +07:00) Bangkok, Hanoi, Jakarta'), ('8.0', '(UTC +08:00) Beijing, Perth, Singapore, Hong Kong'), ('9.0', '(UTC +09:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk'), ('9.5', '(UTC +09:30) Adelaide, Darwin'), ('10.0', '(UTC +10:00) Eastern Australia, Guam, Vladivostok'), ('11.0', '(UTC +11:00) Magadan, Solomon Islands, New Caledonia'), ('12.0', '(UTC +12:00) Auckland, Wellington, Fiji, Kamchatka')], max_length=30),
        ),
    ]
