# Generated by Django 4.1.5 on 2023-01-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_datetimedetails_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecdetails',
            name='sensed_panel_rating',
            field=models.CharField(default='100', max_length=30),
        ),
    ]
