# Generated by Django 4.1.5 on 2023-01-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_datetimedetails_timezone_alter_ecdetails_c1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifidetails',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wifidetails',
            name='ssid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
